### ISSUE TITLE
Create Typescript definitions for sync

### ISSUE THREAD

**Issue by wtrocki** [feedhenry/fh-sync#3]
Add typescript definitions for top level sync api (including configuration)

**Comment by evanshortiss** [comment]
@wtrocki this would be super nice for most of our APIs, the only thing I wonder is how we can generate the TypeScript code for applications? I don't want to check in the generated .js files in my app. If the Deploy called `npm start` instead of `node application.js` I think we could get around this? Example of package.json entry:

```
"start": "tsc && node application.js"
```

**Comment by MikeyBurkman** [comment]
Sweet!

I created a TS sample RHMAP app a while ago. Needs a bit of updating, but I think it still mostly applies: https://github.com/MikeyBurkman/rhmap-ts

@evanshortiss I got around that by using a `postinstall` script that runs the TS compiler.

Also, I have typings written for most of the fh-mbaas-api, including sync. There are a few small issues (look for the `TODO`s), and I haven't touched forms yet, but it's maybe a good place to start. https://github.com/MikeyBurkman/rhmap-ts/blob/master/typings/fh-mbaas-api.d.ts

**Comment by evanshortiss** [comment]
@MikeyBurkman 

![](http://www.reactiongifs.com/r/exc.gif)

**Comment by wtrocki** [comment]
@evanshortiss @MikeyBurkman Thanks a lot for comments! Really appreciate that. 
I will definietly reuse proposed typings for sync! It will save us a lots of time. Thanks again.

To provide context: I'm trying here to refresh sync by removing some legacy stuff and make it independent from platform - so anyone will be able to use it without knowing details of the platform.

**Comment by evanshortiss** [comment]
That's awesome, looking forward to that.

**Comment by paolobueno** [comment]
@MikeyBurkman it's great to know that you can rely on `postinstall` on RHMAP, for RainCatcher we're actually using `prepublish` since we need to push the compiled files to the registry so modules can be used by plain JS code. This also allows us to keep `typescript` and `@types/*` as only `devDependencies`.

**Comment by MikeyBurkman** [comment]
Ah yeah, good point. If it's an end product to be deployed, then postinstall is fine, but if it's a library, then definitely do the TS compilation before sending it to npm.
